from src.common.enums import RegionType

data = [
    {"region_id": RegionType.SEOUL.value[0], "district": "강남구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강남구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강남구", "section": "병"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강동구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강동구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강북구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강북구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강서구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강서구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "강서구", "section": "병"},
    {"region_id": RegionType.SEOUL.value[0], "district": "관악구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "관악구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "광진구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "광진구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "구로구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "구로구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "금천구", "section": None},
    {"region_id": RegionType.SEOUL.value[0], "district": "노원구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "노원구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "노원구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "노원구", "section": "병"},
    {"region_id": RegionType.SEOUL.value[0], "district": "도봉구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "도봉구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "동대문구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "동대문구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "동작구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "동작구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "마포구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "마포구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "서대문구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "서대문구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "서초구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "성동구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "성동구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "성동구", "section": "병"},
    {"region_id": RegionType.SEOUL.value[0], "district": "성북구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "성북구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "송파구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "송파구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "송파구", "section": "병"},
    {"region_id": RegionType.SEOUL.value[0], "district": "양천구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "양천구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "영등포구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "영등포구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "용산구", "section": None},
    {"region_id": RegionType.SEOUL.value[0], "district": "은평구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "은평구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "종로구", "section": None},
    {"region_id": RegionType.SEOUL.value[0], "district": "중구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "중구", "section": "을"},
    {"region_id": RegionType.SEOUL.value[0], "district": "중랑구", "section": "갑"},
    {"region_id": RegionType.SEOUL.value[0], "district": "중랑구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "강서구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "강서구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "금정구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "남구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "남구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "동구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "동래구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "북구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "북구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "사상구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "사하구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "사하구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "서구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "수영구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "연제구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "영도구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "중구", "section": None},
    {"region_id": RegionType.BUSAN.value[0], "district": "진구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "진구", "section": "을"},
    {"region_id": RegionType.BUSAN.value[0], "district": "해운대구", "section": "갑"},
    {"region_id": RegionType.BUSAN.value[0], "district": "해운대구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "강화군", "section": None},
    {"region_id": RegionType.INCHEON.value[0], "district": "계양구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "계양구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "남동구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "남동구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "동구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "동구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "미추홀구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "미추홀구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "부평구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "부평구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "서구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "서구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "연수구", "section": "갑"},
    {"region_id": RegionType.INCHEON.value[0], "district": "연수구", "section": "을"},
    {"region_id": RegionType.INCHEON.value[0], "district": "옹진군", "section": None},
    {"region_id": RegionType.INCHEON.value[0], "district": "중구", "section": None},
    {"region_id": RegionType.DAEGU.value[0], "district": "남구", "section": None},
    {"region_id": RegionType.DAEGU.value[0], "district": "달서구", "section": "갑"},
    {"region_id": RegionType.DAEGU.value[0], "district": "달서구", "section": "을"},
    {"region_id": RegionType.DAEGU.value[0], "district": "달서구", "section": "병"},
    {"region_id": RegionType.DAEGU.value[0], "district": "달성군", "section": None},
    {"region_id": RegionType.DAEGU.value[0], "district": "동구", "section": "갑"},
    {"region_id": RegionType.DAEGU.value[0], "district": "동구", "section": "을"},
    {"region_id": RegionType.DAEGU.value[0], "district": "북구", "section": "갑"},
    {"region_id": RegionType.DAEGU.value[0], "district": "북구", "section": "을"},
    {"region_id": RegionType.DAEGU.value[0], "district": "서구", "section": None},
    {"region_id": RegionType.DAEGU.value[0], "district": "수성구", "section": "갑"},
    {"region_id": RegionType.DAEGU.value[0], "district": "수성구", "section": "을"},
    {"region_id": RegionType.DAEGU.value[0], "district": "중구", "section": None},
    {"region_id": RegionType.GWANGJU.value[0], "district": "광산구", "section": "갑"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "광산구", "section": "을"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "남구", "section": "갑"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "남구", "section": "을"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "동구", "section": "갑"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "동구", "section": "을"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "북구", "section": "갑"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "북구", "section": "을"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "서구", "section": "갑"},
    {"region_id": RegionType.GWANGJU.value[0], "district": "서구", "section": "을"},
    {"region_id": RegionType.DAEJEON.value[0], "district": "대덕구", "section": None},
    {"region_id": RegionType.DAEJEON.value[0], "district": "동구", "section": None},
    {"region_id": RegionType.DAEJEON.value[0], "district": "서구", "section": "갑"},
    {"region_id": RegionType.DAEJEON.value[0], "district": "서구", "section": "을"},
    {"region_id": RegionType.DAEJEON.value[0], "district": "유성구", "section": "갑"},
    {"region_id": RegionType.DAEJEON.value[0], "district": "유성구", "section": "을"},
    {"region_id": RegionType.DAEJEON.value[0], "district": "중구", "section": None},
    {"region_id": RegionType.ULSAN.value[0], "district": "남구", "section": "갑"},
    {"region_id": RegionType.ULSAN.value[0], "district": "남구", "section": "을"},
    {"region_id": RegionType.ULSAN.value[0], "district": "동구", "section": None},
    {"region_id": RegionType.ULSAN.value[0], "district": "북구", "section": None},
    {"region_id": RegionType.ULSAN.value[0], "district": "울주군", "section": None},
    {"region_id": RegionType.ULSAN.value[0], "district": "중구", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "가평군", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "고양시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "고양시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "과천시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "광명시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "광명시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "광주시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "광주시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "구리시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "군포시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "김포시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "김포시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "남양주시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "남양주시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "남양주시", "section": "병"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "부천시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "부천시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "부천시", "section": "병"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "부천시", "section": "정"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "성남시 분당구", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "성남시 분당구", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "성남시 수정구", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "수원특례시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "수원특례시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "수원특례시", "section": "병"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "수원특례시", "section": "정"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안산시 단원구", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안산시 단원구", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안산시 상록구", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안산시 상록구", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안양시 동인구", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안양시 동안구", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "안양시 만안구", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "양주시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "오산시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "용인시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "용인시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "용인시", "section": "병"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "용인시", "section": "정"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "의왕시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "의정부시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "의정부시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "이천시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "파주시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "파주시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "평택시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "평택시", "section": "을"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "포천시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "하남시", "section": None},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "화성시", "section": "갑"},
    {"region_id": RegionType.GYEONGGI.value[0], "district": "화성시", "section": "을"},
    {"region_id": RegionType.SEJONG.value[0], "district": None, "section": "갑"},
    {"region_id": RegionType.SEJONG.value[0], "district": None, "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "강릉시", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "고성군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "동해시", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "삼척시", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "속초시", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "양구군", "section": "갑"},
    {"region_id": RegionType.GANGWON.value[0], "district": "양구군", "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "양양군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "영월군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "원주시", "section": "갑"},
    {"region_id": RegionType.GANGWON.value[0], "district": "원주시", "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "인제군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "정선군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "철원군", "section": "갑"},
    {"region_id": RegionType.GANGWON.value[0], "district": "철원군", "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "춘천시", "section": "갑"},
    {"region_id": RegionType.GANGWON.value[0], "district": "춘천시", "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "태백시", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "평창군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "홍천군", "section": None},
    {"region_id": RegionType.GANGWON.value[0], "district": "화천군", "section": "갑"},
    {"region_id": RegionType.GANGWON.value[0], "district": "화천군", "section": "을"},
    {"region_id": RegionType.GANGWON.value[0], "district": "횡성군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "괴산군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "단양군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "보은군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "영동군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "옥천군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "음성군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "제천시", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "증평군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "진천군", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "청주시 상당구", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "청주시 서원구", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "청주시 청원구", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "청주시 흥덕구", "section": None},
    {"region_id": RegionType.CHUNGBUK.value[0], "district": "충주시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "계룡시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "공주시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "금산군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "논산시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "당진시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "보령시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "부여군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "서산시", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "서천군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "아산시", "section": "갑"},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "아산시", "section": "을"},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "예산군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "천안시", "section": "갑"},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "천안시", "section": "을"},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "천안시", "section": "병"},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "청양군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "태안군", "section": None},
    {"region_id": RegionType.CHUNGNAM.value[0], "district": "홍성군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "고창군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "군산시", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "김제시", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "남원시", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "무주군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "부안군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "순창군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "완주군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "익산시", "section": "갑"},
    {"region_id": RegionType.JEONBUK.value[0], "district": "익산시", "section": "을"},
    {"region_id": RegionType.JEONBUK.value[0], "district": "임실군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "장수군", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "전주시", "section": "병"},
    {"region_id": RegionType.JEONBUK.value[0], "district": "전주시", "section": "갑"},
    {"region_id": RegionType.JEONBUK.value[0], "district": "전주시", "section": "을"},
    {"region_id": RegionType.JEONBUK.value[0], "district": "정읍시", "section": None},
    {"region_id": RegionType.JEONBUK.value[0], "district": "진안군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "강진군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "고흥군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "곡성군", "section": "갑"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "곡성군", "section": "을"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "광양시", "section": "갑"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "광양시", "section": "을"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "구례군", "section": "갑"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "구례군", "section": "을"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "나주시", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "담양군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "목포시", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "무안군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "보성군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "순천시", "section": "갑"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "순천시", "section": "을"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "신안군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "여수시", "section": "갑"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "여수시", "section": "을"},
    {"region_id": RegionType.JEONNAM.value[0], "district": "영광군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "영암군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "완도군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "장성군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "장흥군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "진도군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "함평군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "해남군", "section": None},
    {"region_id": RegionType.JEONNAM.value[0], "district": "화순군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "경산시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "경주시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "고령군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "구미시", "section": "갑"},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "구미시", "section": "을"},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "군위군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "김천시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "문경시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "봉화군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "상주시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "성주군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "안동시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "영덕군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "영양군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "영주시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "영천시", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "예천군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "울릉군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "울진군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "의성군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "청도군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "청송군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "칠곡군", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "포항시 남구", "section": None},
    {"region_id": RegionType.GYEONGBUK.value[0], "district": "포항시 북구", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "거제시", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "거창군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "고성군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "김해시", "section": "갑"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "김해시", "section": "을"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "남해군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "밀양시", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "사천시", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "산청군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "양산시", "section": "갑"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "양산시", "section": "을"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "의령군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "진주시", "section": "갑"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "진주시", "section": "을"},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "창녕군", "section": None},
    {
        "region_id": RegionType.GYEONGNAM.value[0],
        "district": "창원시 마산합포구",
        "section": None,
    },
    {
        "region_id": RegionType.GYEONGNAM.value[0],
        "district": "창원시 마산회원구",
        "section": None,
    },
    {
        "region_id": RegionType.GYEONGNAM.value[0],
        "district": "창원시 성산구",
        "section": None,
    },
    {
        "region_id": RegionType.GYEONGNAM.value[0],
        "district": "창원시 의창구",
        "section": None,
    },
    {
        "region_id": RegionType.GYEONGNAM.value[0],
        "district": "창원시 진해구",
        "section": None,
    },
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "통영시", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "하동군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "함안군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "함양군", "section": None},
    {"region_id": RegionType.GYEONGNAM.value[0], "district": "합천군", "section": None},
    {"region_id": RegionType.JEJU.value[0], "district": "서귀포시", "section": None},
    {"region_id": RegionType.JEJU.value[0], "district": "제주시", "section": "갑"},
    {"region_id": RegionType.JEJU.value[0], "district": "제주시", "section": "을"},
]

