"""Add uuid_jti column

Revision ID: 0003_810e096646b1
Revises: 0002_24d81dcc6840
Create Date: 2023-10-16 00:36:12.703649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_810e096646b1'
down_revision: Union[str, None] = '0002_24d81dcc6840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('uuid_jti', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'uuid_jti')
    # ### end Alembic commands ###
