"""Add email column and delete login_name column of admin

Revision ID: 0005_c024c5eacb27
Revises: 0004_db8df3d4425c
Create Date: 2023-10-17 22:26:43.548989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0005_c024c5eacb27'
down_revision: Union[str, None] = '0004_db8df3d4425c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=256), nullable=False))
    op.drop_index('login_name', table_name='admin')
    op.create_unique_constraint(None, 'admin', ['email'])
    op.drop_column('admin', 'login_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('login_name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_constraint(None, 'admin', type_='unique')
    op.create_index('login_name', 'admin', ['login_name'], unique=False)
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
