"""Insert 21th assembly region data

Revision ID: 0007_baed10e94b88
Revises: 0006_5d39717ac21e
Create Date: 2023-10-23 01:38:56.612606

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table

from src.database.constituency_data.twenty_first import (
    data as twenty_first_assembly_region_list,
)

# revision identifiers, used by Alembic.
revision: str = "0007_baed10e94b88"
down_revision: Union[str, None] = "0006_5d39717ac21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    constituency_table = Table(
        "constituency",
        sa.MetaData(),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("assembly_term", sa.Integer(), nullable=False, comment="국회 회기"),
        sa.Column("region", sa.String(length=256), nullable=False, comment="지역구"),
        sa.Column("district", sa.String(length=256), nullable=True, comment="세부 지역구"),
        sa.Column("section", sa.String(length=256), nullable=True, comment="분구"),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=datetime.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            default=datetime.now(),
            onupdate=datetime.now(),
        ),
    )

    for data in twenty_first_assembly_region_list:
        data["assembly_term"] = 21

    op.bulk_insert(constituency_table, twenty_first_assembly_region_list)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
