"""Insert region and constituency data

Revision ID: 0007_18a952da0b8f
Revises: 0006_62027a38d027
Create Date: 2023-10-28 01:48:34.222312

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table

from src.common.enums import RegionType
from src.database.constituency_data.twenty_first import (
    data as twenty_first_assembly_region_list,
)

# revision identifiers, used by Alembic.
revision: str = "0007_18a952da0b8f"
down_revision: Union[str, None] = "0006_62027a38d027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    region_table = Table(
        "region",
        sa.MetaData(),
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("region", sa.String(length=20), nullable=False, comment="지역구"),
        sa.Column("created_at", sa.DateTime(), default=datetime.now, nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            default=datetime.now,
            onupdate=datetime.now,
            nullable=False,
        ),
    )

    region_static_data = []
    for region in RegionType:
        region_static_data.append(
            {
                "region": region.value[1],
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
            }
        )

    op.bulk_insert(region_table, region_static_data)

    constituency_table = Table(
        "constituency",
        sa.MetaData(),
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("assembly_term", sa.Integer(), nullable=False, comment="국회 회기"),
        sa.Column("region_id", sa.Integer(), nullable=False, comment="지역구 id"),
        sa.Column("district", sa.String(length=20), nullable=True, comment="세부 지역구"),
        sa.Column("section", sa.String(length=20), nullable=True, comment="분구"),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=datetime.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            default=datetime.now(),
            onupdate=datetime.now(),
        ),
    )

    for data in twenty_first_assembly_region_list:
        data["assembly_term"] = 21

    op.bulk_insert(constituency_table, twenty_first_assembly_region_list)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
