"""Create AdminLog model

Revision ID: 0008_6b4c9a7b2441
Revises: 0007_18a952da0b8f
Create Date: 2023-11-27 01:57:55.177151

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0008_6b4c9a7b2441"
down_revision: Union[str, None] = "0007_18a952da0b8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False, comment="관리자 id"),
        sa.Column("politician_id", sa.Integer(), nullable=True, comment="의원 id"),
        sa.Column("action", sa.String(length=50), nullable=False, comment="관리자 활동 종류"),
        sa.Column("detail", sa.JSON(), nullable=True, comment="기타 정보"),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=datetime.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            default=datetime.now(),
            onupdate=datetime.now(),
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin.id"],
        ),
        sa.ForeignKeyConstraint(
            ["politician_id"],
            ["politician.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_log_id"), "admin_log", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_log_id"), table_name="admin_log")
    op.drop_table("admin_log")
    # ### end Alembic commands ###
