"""Add PublicSearchLog model

Revision ID: 0009_365c9eac636a
Revises: 0008_6b4c9a7b2441
Create Date: 2023-12-09 14:22:23.797975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0009_365c9eac636a'
down_revision: Union[str, None] = '0008_6b4c9a7b2441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_search_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_category', sa.String(length=50), nullable=False, comment='검색어 분류'),
    sa.Column('politician_id', sa.Integer(), nullable=True, comment='의원 id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_search_log_id'), 'public_search_log', ['id'], unique=False)
    op.drop_column('constituency', 'assembly_term')
    op.add_column('politician', sa.Column('assembly_term', sa.Integer(), nullable=False, comment='국회 회기'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politician', 'assembly_term')
    op.add_column('constituency', sa.Column('assembly_term', mysql.INTEGER(), autoincrement=False, nullable=False, comment='국회 회기'))
    op.drop_index(op.f('ix_public_search_log_id'), table_name='public_search_log')
    op.drop_table('public_search_log')
    # ### end Alembic commands ###
