"""Change fund field type to BigInteger

Revision ID: 0010_bf7faba0bd78
Revises: 0009_365c9eac636a
Create Date: 2024-01-03 21:53:30.752308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0010_bf7faba0bd78'
down_revision: Union[str, None] = '0009_365c9eac636a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('politician', 'total_required_funds',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='필요 재정 총액',
               existing_nullable=True)
    op.alter_column('politician', 'total_secured_funds',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='확보 재정 총액',
               existing_nullable=True)
    op.alter_column('politician', 'total_executed_funds',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='집행 재정 총액',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('politician', 'total_executed_funds',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_comment='집행 재정 총액',
               existing_nullable=True)
    op.alter_column('politician', 'total_secured_funds',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_comment='확보 재정 총액',
               existing_nullable=True)
    op.alter_column('politician', 'total_required_funds',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_comment='필요 재정 총액',
               existing_nullable=True)
    # ### end Alembic commands ###
