from enum import Enum


class RegionType(Enum):
    """
    대분류 지역구 종류
    - SEOUL = 1, "서울특별시"
    - BUSAN = 2, "부산광역시"
    - INCHEON = 3, "인천광역시"
    - DAEGU = 4, "대구광역시"
    - GWANGJU = 5, "광주광역시"
    - DAEJEON = 6, "대전광역시"
    - ULSAN = 7, "울산광역시"
    - GYEONGGI = 8, "경기"
    - SEJONG = 9, "세종특별시"
    - GANGWON = 10, "강원"
    - CHUNGBUK = 11, "충북"
    - CHUNGNAM = 12, "충남"
    - JEONBUK = 13, "전북"
    - JEONNAM = 14, "전남"
    - GYEONGBUK = 15, "경북"
    - GYEONGNAM = 16, "경남"
    - JEJU = 17, "제주"
    """

    SEOUL = 1, "서울특별시"
    BUSAN = 2, "부산광역시"
    INCHEON = 3, "인천광역시"
    DAEGU = 4, "대구광역시"
    GWANGJU = 5, "광주광역시"
    DAEJEON = 6, "대전광역시"
    ULSAN = 7, "울산광역시"
    GYEONGGI = 8, "경기"
    SEJONG = 9, "세종특별시"
    GANGWON = 10, "강원"
    CHUNGBUK = 11, "충북"
    CHUNGNAM = 12, "충남"
    JEONBUK = 13, "전북"
    JEONNAM = 14, "전남"
    GYEONGBUK = 15, "경북"
    GYEONGNAM = 16, "경남"
    JEJU = 17, "제주"
